# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven" # Phải là chữ thường, nằm trong ngoặc kép
    directory: "/" # Thư mục chứa file pom.xml
    schedule:
      interval: "weekly" # Tần suất quét (daily, weekly, monthly)
    open-pull-requests-limit: 5 # Giới hạn số lượng PR do Dependabot tạo ra
